version 0.2

phase:
    install:
        runtime-versions:
            nodejs: 10
    pre_build:
        commands:
            #run 'npm install' using version in package-lock.json
            - npm ci
    builds:
        commands: 
            - npm run build
artifacts:
    files:
        - start-service.sh
        - stop-service.sh
        - server.js
        - package.json
        - appspec.yml
        - 'noe_modules/**/*'